#!/bin/bash

mkdir /etc/phroses && chown www-data /etc/phroses
read -p "Enable site and restart apache? (Y/n): " answer

if [[ "$answer" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    a2enmod rewrite
    a2ensite phroses
    service apache2 restart
fi;