#!/bin/bash

if [[ ! -d /etc/phroses ]]; then
    mkdir /etc/phroses && chown www-data /etc/phroses
fi

read -p "Enable phroses and restart apache? (Y/n): " answer

if [[ "$answer" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    a2enmod rewrite
    a2enconf phroses
    service apache2 restart
fi;