language: php

php:
- '7.2'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq postfix

before_script:
# add config
- echo "$(echo "$DEPLOY_KEY" | base64 --decode)" > config/deploy.key
- phpenv config-add config/php.ini
- mv config/phroses.conf phroses.conf

# install dependencies
- export PATH=$PWD/vendor/bin:$(npm bin):$PATH
- npm install -g bower
- composer install

# setup mysql
- sudo mysql -e 'CREATE DATABASE phroses;'
- sudo mysql phroses < src/schema/install.sql
- sudo mysql phroses -e "show tables"

# setup postfix
- sudo service postfix stop
- smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
- echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
- echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php
  -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

script:
- composer run test

after_success:
- ./scripts/deploy.sh

addons:
  mariadb: '10.2'
  ssh_known_hosts:
  - deb.cythral.com
