language: php

php:
  - '7.0'
  - '7.1'
  
script:
  php build.php
  php tests/bootstrap.php
  
deploy:
  provider: releases
  api_key: "8854d7ecf6942dbeead6e478913419f551f45fef"
  file: "phroses.tar.gz"
  skip_cleanup: true
  on:
    tags: true