ALTER TABLE `pages` ADD `css` LONGTEXT NULL;
ALTER TABLE `sites` ADD `adminIP` varchar(200) NOT NULL AFTER `adminURI`;
UPDATE `options` SET `value`='4' WHERE `key`='schemaver';

ALTER TABLE `sites` MODIFY COLUMN `url` VARCHAR(255);
ALTER TABLE `sessions` MODIFY COLUMN `id` VARCHAR(255);
ALTER TABLE `pages` MODIFY COLUMN `uri` VARCHAR(255);

ALTER TABLE `pages` ADD CONSTRAINT `pages_siteID_fk` 
    FOREIGN KEY (`siteID`) REFERENCES `sites` (`id`)
    ON DELETE CASCADE;

/** CONVERT CHARSETS */
ALTER TABLE `options` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `sessions` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `pages` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `sites` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

/** CONVERT ENGINES **/
ALTER TABLE `options` ENGINE=InnoDB;
ALTER TABLE `sessions` ENGINE=InnoDB;
ALTER TABLE `pages` ENGINE=InnoDB;
ALTER TABLE `sites` ENGINE=InnoDB;

